background = 0xFF0F0F0F
base = 0xFF1A1816
text = 0xFFEADCCC
alternate_base = 0xFF211E1B
bright_text = 0xFFE2BE8A
accent = 0xFFE2BE8A
link_text = 0xFFE2BE8A
accent_secondary = 0xFFEACEA7
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
