# theme: sunset-float
background              #0F0F0F
foreground              #EADCCC
cursor                  #EADCCC
cursor_text_color       #0F0F0F
selection_foreground    #EADCCC
selection_background    #E2BE8A
active_tab_background   #1A1816
active_tab_foreground   #E2BE8A
inactive_tab_background #211E1B
inactive_tab_foreground #A98C72

color0  #0F0F0F
color1  #E25D6C
color2  #CEA37F
color3  #F4BB54
color4  #E2BE8A
color5  #EDE4C8
color6  #E8AB3B
color7  #E6CAAB
color8  #706A6A
color9  #E9838F
color10 #CEA37F
color11 #EDB95A
color12 #EACEA7
color13 #EDE4C8
color14 #ECB95C
color15 #EADCCC

background_opacity 0.90
